name: Publish the MirrorHash package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set new version
        run: |
          git config --global user.email ${{ secrets.GITHUB_USER_MAIL }}
          git config --global user.name ${{ secrets.GITHUB_USER_NAME }}
          npm version "${{vars.RELEASE_ID}}.${{ github.run_id }}"
        shell: bash

      - name: Set token to the registry
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_API_KEY }}
        shell: bash

      - name: Publish the package
        run: |
          npm publish
        shell: bash
